/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Alimentos': RouteRecordInfo<'/Alimentos', '/Alimentos', Record<never, never>, Record<never, never>>,
    '/Carne': RouteRecordInfo<'/Carne', '/Carne', Record<never, never>, Record<never, never>>,
    '/Tambo': RouteRecordInfo<'/Tambo', '/Tambo', Record<never, never>, Record<never, never>>,
  }
}
